spring:
  application:
    name: eph-code
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.EphAI.Eph_Code.controller
